-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 12:34:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ESTACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTACION` (
  `Codigo` INT NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `IP` VARCHAR(45) NOT NULL,
  `Ubicacion` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VARIABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VARIABLE` (
  `Codigo` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SENSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SENSOR` (
  `Codigo` INT NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONTIENE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONTIENE` (
  `ESTACION_Codigo` INT NOT NULL,
  `SENSOR_Codigo` INT NOT NULL,
  PRIMARY KEY (`ESTACION_Codigo`, `SENSOR_Codigo`),
  INDEX `fk_ESTACION_has_SENSOR_SENSOR1_idx` (`SENSOR_Codigo` ASC) VISIBLE,
  INDEX `fk_ESTACION_has_SENSOR_ESTACION_idx` (`ESTACION_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_ESTACION_has_SENSOR_ESTACION`
    FOREIGN KEY (`ESTACION_Codigo`)
    REFERENCES `mydb`.`ESTACION` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTACION_has_SENSOR_SENSOR1`
    FOREIGN KEY (`SENSOR_Codigo`)
    REFERENCES `mydb`.`SENSOR` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALMACENA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ALMACENA` (
  `SENSOR_Codigo` INT NOT NULL,
  `VARIABLE_Codigo` INT NOT NULL,
  PRIMARY KEY (`SENSOR_Codigo`, `VARIABLE_Codigo`),
  INDEX `fk_SENSOR_has_VARIABLE_VARIABLE1_idx` (`VARIABLE_Codigo` ASC) VISIBLE,
  INDEX `fk_SENSOR_has_VARIABLE_SENSOR1_idx` (`SENSOR_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_SENSOR_has_VARIABLE_SENSOR1`
    FOREIGN KEY (`SENSOR_Codigo`)
    REFERENCES `mydb`.`SENSOR` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SENSOR_has_VARIABLE_VARIABLE1`
    FOREIGN KEY (`VARIABLE_Codigo`)
    REFERENCES `mydb`.`VARIABLE` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MIDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MIDE` (
  `SENSOR_Codigo` INT NOT NULL,
  `VARIABLE_Codigo` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SENSOR_Codigo`, `VARIABLE_Codigo`, `hora`, `valor`, `fecha`),
  INDEX `fk_SENSOR_has_VARIABLE_VARIABLE2_idx` (`VARIABLE_Codigo` ASC) VISIBLE,
  INDEX `fk_SENSOR_has_VARIABLE_SENSOR2_idx` (`SENSOR_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_SENSOR_has_VARIABLE_SENSOR2`
    FOREIGN KEY (`SENSOR_Codigo`)
    REFERENCES `mydb`.`SENSOR` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SENSOR_has_VARIABLE_VARIABLE2`
    FOREIGN KEY (`VARIABLE_Codigo`)
    REFERENCES `mydb`.`VARIABLE` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
